AllCops:
  Include:
    - metadata.rb
    - Gemfile
    - attributes/**
    - recipes/**
    - libraries/**
    - providers/**
    - resources/**
  Exclude:
    - example/**
    - test/**/*
    - vendor/**

Encoding:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

Documentation:
  Enabled: false

MethodLength:
  Max: 20

ClassAndModuleCamelCase:
  Enabled: false
